[package]
name = "samp-plugin"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]

[lib]
name = "plugin"
crate-type = ["dylib"]

[dependencies]
samp-sdk = { git = "https://github.com/zottce/samp-sdk.git" }